const actionTypes =  {

    // fetching
    TOGGLE_IS_FETCHING: "TOGGLE_IS_FETCHING",

    // filter
    GET_SORT_CATEGORIES: "GET_SORT_CATEGORIES",
    CHANGE_CURRENT_CATEGORY: "CHANGE_CURRENT_CATEGORY",

    //header
    SET_CATEGORIES: 'SET_CATEGORIES',
    TOGGLE_MENU_STATE:'TOGGLE_MENU_STATE',
    SET_MENU: 'SET_MENU',

    // home
    SET_MAIN_SLIDER: "SET_MAIN_SLIDER",
    SET_HOME_SLIDER: "SET_HOME_SLIDER",

    // menu
    REQUEST_MENU_CATEGORIES: "REQUEST_MENU_CATEGORIES",

    // catalog
    SET_PIZZA: "SET_PIZZA",
    CHANGE_FAST_CATEGORY: "CHANGE_FAST_CATEGORY",
}

export default actionTypes